import type { ArtifactDeclaration } from "./chain-walker"

const HEADER = `// Auto-generated by @wolder/ts-plugin — do not edit manually
import type { Artifact, MemberRef } from "@wolder/core"
`

export function generateArtifactTypes(declarations: ArtifactDeclaration[]): string {
  if (declarations.length === 0) {
    return HEADER
  }

  const lines = [HEADER]

  for (const decl of declarations) {
    const typeName = capitalize(decl.variableName) + "Artifact"

    if (decl.memberNames.length === 0) {
      lines.push(`export type ${typeName} = Artifact<Record<string, never>>`)
    } else {
      const memberLines = decl.memberNames.map(
        (name) => `  ${name}: MemberRef<"${name}">`
      )
      lines.push(`export type ${typeName} = Artifact<{`)
      lines.push(memberLines.join("\n"))
      lines.push(`}>`)
    }

    lines.push("")
  }

  return lines.join("\n")
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
