import { describe, it, expect } from "vitest"
import { generateArtifactTypes } from "./generate-types"
import type { ArtifactDeclaration } from "./chain-walker"

describe("generateArtifactTypes", () => {
  it("generates types for a single artifact with members", () => {
    const decls: ArtifactDeclaration[] = [
      { variableName: "todoService", memberNames: ["getAllItems", "addItem"] },
    ]

    const output = generateArtifactTypes(decls)

    expect(output).toContain('import type { Artifact, MemberRef } from "@wolder/core"')
    expect(output).toContain("export type TodoServiceArtifact = Artifact<{")
    expect(output).toContain('  getAllItems: MemberRef<"getAllItems">')
    expect(output).toContain('  addItem: MemberRef<"addItem">')
    expect(output).toContain("}>")
  })

  it("generates types for artifact with no members", () => {
    const decls: ArtifactDeclaration[] = [
      { variableName: "app", memberNames: [] },
    ]

    const output = generateArtifactTypes(decls)

    expect(output).toContain(
      "export type AppArtifact = Artifact<Record<string, never>>",
    )
  })

  it("generates types for multiple artifacts", () => {
    const decls: ArtifactDeclaration[] = [
      { variableName: "svc", memberNames: ["run"] },
      { variableName: "ctrl", memberNames: ["handle", "register"] },
    ]

    const output = generateArtifactTypes(decls)

    expect(output).toContain("export type SvcArtifact = Artifact<{")
    expect(output).toContain("export type CtrlArtifact = Artifact<{")
    expect(output).toContain('  handle: MemberRef<"handle">')
    expect(output).toContain('  register: MemberRef<"register">')
  })

  it("returns header only for empty declarations", () => {
    const output = generateArtifactTypes([])

    expect(output).toContain("Auto-generated by @wolder/ts-plugin")
    expect(output).not.toContain("export type")
  })

  it("capitalizes variable name for type name", () => {
    const decls: ArtifactDeclaration[] = [
      { variableName: "myService", memberNames: ["get"] },
    ]

    const output = generateArtifactTypes(decls)

    expect(output).toContain("export type MyServiceArtifact")
  })
})
