import { readFileSync, existsSync } from "node:fs"
import { resolve } from "node:path"
import type { NodeDefinition, InputRef, Artifact, MemberRef, Plugin } from "./types.js"

export function buildSystemPrompt(): string {
  return `You are a code generator. You will generate or modify files within a specified scope. Files listed as INPUT are read-only context — do not modify them. Files listed as SCOPE are your output targets.

Output ONLY the content of each scoped file, formatted as:
=== FILE: <path> ===
<content>
=== END FILE ===

Do not include any explanation, commentary, or markdown fencing. Output only the file blocks.`
}

export function buildUserPrompt(
  node: NodeDefinition,
  root: string,
  preGeneratedInputs: Array<{ path: string; content: string }> = [],
): string {
  const parts: string[] = []

  // Scope files
  parts.push("SCOPE FILES (you will generate these):")
  for (const file of node.scopeFiles) {
    parts.push(`- ${file}`)
  }
  parts.push("")

  // Input files (declared + pre-generated by plugins)
  const inputFiles = collectInputContent(node.inputs, root)
  const allInputs = [...inputFiles, ...preGeneratedInputs]
  if (allInputs.length > 0) {
    parts.push("INPUT FILES (read-only context):")
    for (const { path, content } of allInputs) {
      parts.push(`=== FILE: ${path} ===`)
      parts.push(content)
      parts.push("=== END FILE ===")
      parts.push("")
    }
  }

  // Instruction
  parts.push("INSTRUCTION:")
  parts.push(node.actInstruction.trim())
  parts.push("")

  // Expectations — core file checks + plugin-formatted
  const expLines = formatAllExpectations(node.expectations, node.plugins)
  if (expLines.length > 0) {
    parts.push("EXPECTATIONS (your output must satisfy these):")
    for (const line of expLines) {
      parts.push(`- ${line}`)
    }
  }

  return parts.join("\n")
}

function collectInputContent(
  inputs: Array<InputRef | Artifact | MemberRef>,
  root: string,
): Array<{ path: string; content: string }> {
  const results: Array<{ path: string; content: string }> = []
  const seen = new Set<string>()

  for (const input of inputs) {
    if (input.kind === "input") {
      const absPath = resolve(root, input.path)
      if (!seen.has(input.path) && existsSync(absPath)) {
        seen.add(input.path)
        results.push({ path: input.path, content: readFileSync(absPath, "utf-8") })
      }
    } else if (input.kind === "member") {
      const absPath = resolve(root, input.filePath)
      if (!seen.has(input.filePath) && existsSync(absPath)) {
        seen.add(input.filePath)
        results.push({ path: input.filePath, content: readFileSync(absPath, "utf-8") })
      }
    } else {
      for (const file of input.generatedFiles) {
        const absPath = resolve(root, file)
        if (!seen.has(file) && existsSync(absPath)) {
          seen.add(file)
          results.push({ path: file, content: readFileSync(absPath, "utf-8") })
        }
      }
    }
  }

  return results
}

function formatAllExpectations(
  expectations: Array<{ type: string; path?: string }>,
  plugins: Plugin<any>[],
): string[] {
  const lines: string[] = []

  for (const exp of expectations) {
    if (exp.type === "file") {
      lines.push(`A file named "${exp.path}" must exist`)
      continue
    }

    for (const plugin of plugins) {
      if (plugin.expectationTypes.includes(exp.type)) {
        lines.push(...plugin.formatExpectations([exp as any]))
        break
      }
    }
  }

  return lines
}
